import { Injectable } from '@angular/core';
import { jsPDF } from 'jspdf';
import { Prescription, ClinicalNote } from '../../../core/models/clinical.model';
import { Patient } from '../../../core/models/patient.model';
import { Vitals } from '../../../core/models/vitals.model';

@Injectable({
    providedIn: 'root',
})
export class PrescriptionExportService {
    constructor() { }

    public generatePrescriptionPDF(
        prescription: Prescription,
        patient: Patient,
        vitals: Vitals | null,
        note: ClinicalNote | null
    ): void {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        let y = 20;

        // Header
        doc.setFontSize(22);
        doc.setTextColor(41, 128, 185);
        doc.text('MEDICAL CENTER', pageWidth / 2, y, { align: 'center' });
        y += 10;
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('Outpatient Care (OPC) System | Prescription', pageWidth / 2, y, { align: 'center' });
        y += 5;
        doc.line(20, y, pageWidth - 20, y);
        y += 15;

        // Patient Info
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.setFont('helvetica', 'bold');
        doc.text(`Patient: ${patient.fullName}`, 20, y);
        doc.text(`Date: ${new Date(prescription.date).toLocaleDateString()}`, pageWidth - 20, y, { align: 'right' });
        y += 7;
        doc.setFont('helvetica', 'normal');
        doc.text(`ID: ${patient.id} | Age: ${patient.age} | Gender: ${patient.gender}`, 20, y);
        y += 15;

        // Vitals Section
        if (vitals) {
            doc.setFillColor(245, 245, 245);
            doc.rect(20, y, pageWidth - 40, 15, 'F');
            doc.setFont('helvetica', 'bold');
            doc.text('Vitals:', 25, y + 10);
            doc.setFont('helvetica', 'normal');
            doc.text(`Temp: ${vitals.temperature}°F | BP: ${vitals.bloodPressure?.systolic}/${vitals.bloodPressure?.diastolic} | SpO2: ${vitals.spo2}% | Wt: ${vitals.weight}kg`, 50, y + 10);
            y += 25;
        }

        // Clinical Notes
        if (note) {
            doc.setFont('helvetica', 'bold');
            doc.text('Chief Complaints:', 20, y);
            y += 6;
            doc.setFont('helvetica', 'normal');
            doc.text(note.complaints.join(', '), 25, y);
            y += 10;

            doc.setFont('helvetica', 'bold');
            doc.text('Diagnosis:', 20, y);
            y += 6;
            doc.setFont('helvetica', 'normal');
            doc.text(note.diagnosis || 'N/A', 25, y);
            y += 15;
        }

        // Prescription Section
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(41, 128, 185);
        doc.text('Rx - MEDICINES', 20, y);
        y += 10;

        doc.setFontSize(11);
        doc.setTextColor(0);
        prescription.medicines.forEach((med, index) => {
            doc.setFont('helvetica', 'bold');
            doc.text(`${index + 1}. ${med.medicineName} (${med.dosage})`, 25, y);
            y += 5;
            doc.setFont('helvetica', 'normal');
            doc.text(`   Frequency: ${med.frequency} | Duration: ${med.duration} | Timing: ${med.timing.replace('_', ' ')}`, 25, y);
            y += 10;

            // Page break check
            if (y > 270) {
                doc.addPage();
                y = 20;
            }
        });

        if (prescription.instructions) {
            y += 5;
            doc.setFont('helvetica', 'bold');
            doc.text('Instructions:', 20, y);
            y += 6;
            doc.setFont('helvetica', 'normal');
            const splitInstructions = doc.splitTextToSize(prescription.instructions, pageWidth - 40);
            doc.text(splitInstructions, 25, y);
        }

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text('Signature', pageWidth - 50, 270);
        doc.line(pageWidth - 70, 265, pageWidth - 30, 265);
        doc.text('Generated by Antigravity OPC System', pageWidth / 2, 285, { align: 'center' });

        // Save PDF
        doc.save(`Prescription_${patient.fullName.replace(' ', '_')}_${new Date().getTime()}.pdf`);
    }
}
